### ISSUE TITLE
Not running smoothly on Android

### ISSUE THREAD

**Issue by RotemShaanan** [zeljkoX/react-native-loading-placeholder#1]
Hey!

I'm using this library for the same purpose.
On iOS it looks really great, but on Android it doesn't look good - the gradient looses shape, and it looks like a gray line with a trail that's moving.

Did anyone encounter this issue too?

Thanks!

This is how it looks on an Android device:
![screen shot 2017-10-23 at 18 54 07](https://user-images.githubusercontent.com/11707185/31899304-e6ea233c-b823-11e7-8944-d8fd495cd1c5.png)

This is on iPhone:
![photo_2017-10-23_18-55-50](https://user-images.githubusercontent.com/11707185/31899305-e70bbe84-b823-11e7-9efa-5f2483cde2f0.jpg)

**Comment by tiberiumihai** [comment]
This is because this library is not using useNativeDriver. I've added a PR for this here: https://github.com/zeljkoX/react-native-loading-placeholder/pull/2

**Comment by RotemShaanan** [comment]
I tried this too and it didn't help,
My problem was caused because i created a linear gradient that is bigger than the placeholder itself (i don't know why it explains it, but changing it solved it).

**Comment by tiberiumihai** [comment]
I had a similar issue and for me useNativeDriver helped to get the animation more fluid. 

For your case, it's good to know that we need to use the same dimensions for both: gradient and placeholder.

**Comment by zeljkoX** [comment]
@tiberiumihai  Tnx for PR.
