### ISSUE TITLE
For placeholders placed next to each other a row, individual animation isn't running.

### ISSUE THREAD

**Issue by hjaintech** [zeljkoX/react-native-loading-placeholder#10]
I have 3 cards that placed horizontally in a row. Now when the animation happens, it happens from left to right of the screen. Instead animation should happen from left to right of each card placeholder.

**Comment by zeljkoX** [comment]
@hjaintech

This library is indented to work that way.

In order to accomplish your use case, You can wrap every Placeholder in its own PlaceholderContainer.
```
<PlaceholderContainer>
    <Placeholder />
<PlaceholderContainer>
<PlaceholderContainer>
    <Placeholder />
<PlaceholderContainer>
<PlaceholderContainer>
    <Placeholder />
<PlaceholderContainer>
```
