### ISSUE TITLE
CRNA error

### ISSUE THREAD

**Issue by dhruvdutt** [zeljkoX/react-native-loading-placeholder#4]
Doesn't work with create-react-native-app that uses Expo.
The issue seems to coming from react-native-linear-gradient which has native dependencies.
[#157](https://github.com/react-native-community/react-native-linear-gradient/issues/157) might help.

**Comment by zeljkoX** [comment]
@dhruvdutt 
This package is open to use in many ways. 
If you are using example from front page, in order to use it with Expo
replace 
import LinearGradient from 'react-native-linear-gradient';
with
import { LinearGradient } from 'expo';
