### ISSUE TITLE
How to ensure multiple PlaceHolderContainers animate in sync?

### ISSUE THREAD

**Issue by isaachinman** [zeljkoX/react-native-loading-placeholder#7]
Thanks for a cool project! I just pulled this into my own app and copy/pasted a couple of your example components in a row:

    <PlaceholderContainer
      style={styles.placeholderContainer}
      animatedComponent={<Gradient />}
      duration={1000}
      delay={1000}
      key={`loading-ui-placeholder-${id}`}
    >
      <View style={{ flexDirection: 'row' }}>
        <Placeholder style={[styles.placeholder, { width: 50, height: 50 }]} />
        <View
          style={{
            flexDirection: 'column',
            width: '100%',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Placeholder
            style={[
              styles.placeholder,
              {
                width: '50%',
                height: 10,
              },
            ]}
          />
          <Placeholder
            style={[
              styles.placeholder,
              {
                width: '35%',
                height: 7,
              },
            ]}
          />
        </View>
      </View>

      <Placeholder
        style={[styles.placeholder, { marginTop: 20, width: '80%' }]}
      />
      <Placeholder style={[styles.placeholder, { width: '90%' }]} />
      <Placeholder style={[styles.placeholder, { width: '50%' }]} />
    </PlaceholderContainer>

Obviously, just one of these animates nicely with no problems. After putting two in a row, they begin to animate simultaneously, but after several cycles become out of sync, and look strange next to each other. I can upload a gif if necessary but I think it's pretty self explanatory.

Is there any way we can provide the animation lifecycle directly, instead of passing these millisecond props? It seems something is offsetting animation.

**Comment by zeljkoX** [comment]
Hello

If you copied code example multiple times then you are having more than one PlaceholderContainer component.

One solution is to have only one PlaceholderContainer component for synchronised animation. 

So lets say you need Placeholders for 3 loading images.

Instead of using PlaceholderContainer three times as  consider using it once with three components used as image placeholders. That way it will be synced.

```
<PlaceholderContainer>
   <PlaceholderImage/>
   <PlaceholderImage/>
   <PlaceholderImage/>
</PlaceholderContainer>
```

PlaceholderImage can contain multiple Placeholder components and have any style.

```
const PlaceholderImage = () => (
  <View>
   <Placeholder
          style={{
              width: 100,
              height: 100
            }}
        />
   <Placeholder
          style={{
              width: 100,
              height: 10
            }}
        />
  </View>
)
```

**Comment by isaachinman** [comment]
Got it, thanks. I was indeed creating multiple `PlaceholderContainer`s in a map. I assume this is using the context API or something similar, and that you could probably get away with putting a `PlaceholderContainer` at the root of your app and just putting placeholders where ever you wanted? Or would this have performance implications?

Either way, nice project!
