### ISSUE TITLE
Can't Use By Native Base

### ISSUE THREAD

**Issue by loverdeveloper** [zeljkoX/react-native-loading-placeholder#8]
Hi , i Use Native Base in My App ,How i Can Use "react-native-loading-placeholder" ?

**Comment by zeljkoX** [comment]
Are you using it with expo?

If you do in example change LinearGradient import, import it from expo not LinearGradient package.

**Comment by loverdeveloper** [comment]
No , i don't use expo!

**Comment by zeljkoX** [comment]
Provide a usage example and error stack you are receiving.
